name: CI - CD

on:
  push:
    branches: 
      - 'master'

jobs:
  jobs-1:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Cache composer depedencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock')}}
      - name: Run composer install
        run: composer install
        env:
          APP_ENV: testing
      - name: Run composer update
        run: composer update
      # - name: Run testing
      #   run: ./vendor/bin/phpunit
    