name: CI - CD

on:
  push:
    branches: 
      - 'master'

jobs:

  jobs-1:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Cache composer depedencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock')}}
      - name: Run composer install
        run: composer install
        env:
          APP_ENV: testing
      - name: Run composer update
        run: composer update
      - name: Generate config file
        env:
          CONFIG: ${{secrets.CONFIG_APP}}
        run: | 
          echo "$CONFIG" > .env
      - run: ls
      - name: Run testing
        run: ./vendor/bin/phpunit
  
  jobs-2:
    name: Build image
    runs-on: ubuntu-20.04
    needs: jobs-1
    steps:
      - uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Cache composer depedencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock')}}
      - name: Run composer install
        run: composer install
      - name: Run composer update
        run: composer update
      - name: Generate config file
        env:
          CONFIG: ${{secrets.CONFIG_APP}}
        run: | 
          echo "$CONFIG" > .env
      - name: Build image
        run: docker build -t mhakim/outlet:1.0 .
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: push to docker hub
        run: docker push mhakim/outlet:1.0

  jobs-3:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: jobs-2
    steps:
      - name: Setup server
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          host: ${{secrets.HOST}}
          sync: false
          script_stop: true
          script: |
            docker pull mhakim/outlet:1.0
            docker images
            docker stop majoo_apps
            docker rm majoo_apps
            docker run -d -p 80:80 -p 8000:8000 --name majoo_apps mhakim/outlet:1.0
            docker container ps
      

    