name: CI - CD

on:
  push:
    branches: 
      - 'master'

jobs:
  jobs-1:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache composer depedencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock')}}
      - name: Run composer update
        run: composer
      - name: Prepare Laravel Application
        run: | 
          cd /var/www/html
          composer install --ignore-platform-reqs
      - run: ls
    